dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
  global:
  - PGPORT=5432
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - python manage.py migrate
language: python
python:
  - "3.6"
env: 
- DJANGO=2.0 DB=postgres
before_install: 
- cd cabina/decide
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
